inherit_gem:
  rubocop-gp:
    - ./config/default.yml

AllCops:
  TargetRubyVersion: 3.0

Rails/ApplicationRecord:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Style/Next:
  Enabled: false

Style/ClassVars:
 Enabled: false
