inherit_gem:
  rubocop-gp:
    - ./config/default.yml

AllCops:
  TargetRubyVersion: 3.0

Rails/ApplicationRecord:
  Enabled: false

Rails/Output:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Style/Next:
  Enabled: false

Style/ClassVars:
 Enabled: false

Gp/UnsafeYamlMarshal:
  Enabled: true
  Exclude:
    - spec/**/*.rb

Gp/OptArgParameters:
  Enabled: false
